routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Session::has('login')) {
        return redirect('dashboard');
    }
    return redirect('login');
});
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/doLogin', 'AuthController@login')->name('doLogin');
Route::get('/logout', 'AuthController@logout')->name('logout');


//course
Route::resource('course', 'CourseController');
Route::get('/data/course', 'CourseController@dataTable')->name('data.course');

//lecturer
Route::resource('lecturer', 'LecturerController');
Route::get('/data/lecturer', 'LecturerController@dataTable')->name('data.lecturer');

//collegestudent
Route::resource('collegestudent', 'CollegeStudentController');
Route::get('/data/collegestudent', 'CollegeStudentController@dataTable')->name('data.collegestudent');

//grade
Route::resource('grade', 'GradeController');
Route::get('/data/grade', 'GradeController@dataTable')->name('data.grade');

//academicyear
Route::resource('academicyear', 'AcademicyearController');
Route::get('/data/academicyear', 'AcademicyearController@dataTable')->name('data.academicyear');

//teach
Route::resource('teach', 'TeachController');
Route::get('/data/teach', 'TeachController@dataTable')->name('data.teach');

//user
Route::resource('user', 'UserController');
Route::get('/data/user', 'UserController@dataTable')->name('data.user');

//auth

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    protected $table = 'users';
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = User::all();
        return view('pages.user.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new User();
        return view('pages.user.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required|size:8'
        ]);

        $model = User::insert([
            [
                'name' => $request->name,
                'email' => $request->email,
                'password' => bcrypt($request->password),
                'level' => $request->level
            ]
        ]);
        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = User::findOrFail($id);
        return view('pages.user.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = User::findOrFail($id);
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = User::findOrFail($id);
        $model->delete();
    }

    public function dataTable()
    {
        $model = User::query();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layout._actionuser', [
                    'model' => $model,
                    'url_edit' => route('user.edit', $model->id),
                    'url_destroy' => route('user.destroy', $model->id),
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make('true');
    }
}

resources/views/pages/user/form.blade.php
{!! Form::model($model, [
'route' => $model->exists ? ['user.update', $model->id] : 'user.store',
'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

<div class="col-md-12">
    <div class="form-group">
        <label>Nama Pengguna</label>
        {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Email</label>
        {{ Form::text('email', null, ['class' => 'form-control', 'id' => 'email']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Password</label>
        {{ Form::password('password', ['class' => 'form-control', 'id' => 'password']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Level</label>
        {!! Form::select('level', ['admin' => 'Admin', 'dosen' => 'Dosen'], ['class' => 'form-control', 'id' => 'level']) !!}
    </div>
</div>

{!! Form::close() !!}

resources/views/pages/user/index.blade.php
@extends('layout/nav_side_foot')
@section('title','SIN | Mata Kuliah')
@section('container')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">DATA PENGGUNA</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Data Pengguna</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Pengguna</h3>
                <div class="float-sm-right">
                <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm float-sm-right modal-show" title="Tambah Data Pengguna">
                    <i class="fas fa-plus"></i>  Tambah
                </a>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">

                  <thead>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Pengguna</th>
                    <th>Nama Pengguna</th>
                    <th>Email</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>

                  <tbody></tbody>

                  <tfoot>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Pengguna</th>
                    <th>Nama Pengguna</th>
                    <th>Email</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  @endsection
  @push('js')
  <script>
  $(function () {
    $("#table").DataTable({
      processing: true,
      serverSide: true,
      responsive: true,
      ajax: "{{ route('data.user') }}",
      columns: [
        {data: 'DT_RowIndex', name: 'id'},
        {data: 'id', name: 'id'},
        {data: 'name', name: 'name'},
        {data: 'email', name: 'email'},
        {data: 'action', name: 'action'}
      ]

    });
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
  </script>
  @endpush