routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Session::has('login')) {
        return redirect('dashboard');
    }
    return redirect('login');
});
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/doLogin', 'AuthController@login')->name('doLogin');
Route::get('/logout', 'AuthController@logout')->name('logout');


//course
Route::resource('course', 'CourseController');
Route::get('/data/course', 'CourseController@dataTable')->name('data.course');

//lecturer
Route::resource('lecturer', 'LecturerController');
Route::get('/data/lecturer', 'LecturerController@dataTable')->name('data.lecturer');

//collegestudent
Route::resource('collegestudent', 'CollegeStudentController');
Route::get('/data/collegestudent', 'CollegeStudentController@dataTable')->name('data.collegestudent');

//grade
Route::resource('grade', 'GradeController');
Route::get('/data/grade', 'GradeController@dataTable')->name('data.grade');

//academicyear
Route::resource('academicyear', 'AcademicyearController');
Route::get('/data/academicyear', 'AcademicyearController@dataTable')->name('data.academicyear');

//teach
Route::resource('teach', 'TeachController');
Route::get('/data/teach', 'TeachController@dataTable')->name('data.teach');

//user
Route::resource('user', 'UserController');
Route::get('/data/user', 'UserController@dataTable')->name('data.user');

//auth

app/Academicyear.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Academicyear extends Model
{
    protected $primaryKey = 'idacad';
    protected $guarded = [];
}

app/Http/Controllers/AcademicyearController.php
<?php

namespace App\Http\Controllers;

use App\Academicyear;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;

class AcademicyearController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Academicyear::all();
        return view('pages.academicyear.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Academicyear();
        return view('pages.academicyear.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'tahun_akademik' => 'required'
        ]);
        $model = Academicyear::create($request->all());
        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Academicyear  $academicyear
     * @return \Illuminate\Http\Response
     */
    public function show(Academicyear $academicyear)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Academicyear  $academicyear
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Academicyear::findOrFail($id);
        return view('pages.academicyear.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Academicyear  $academicyear
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Academicyear::findOrFail($id);
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Academicyear  $academicyear
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Academicyear::findOrFail($id);
        $model->delete();
    }

    public function dataTable()
    {
        $model = Academicyear::query();
        return DataTables::of($model)
        ->addColumn('action', function ($model){
            return view('layout._actionacad', [
                'model' => $model,
                'url_edit' => route('academicyear.edit', $model->idacad),
                'url_destroy' => route('academicyear.destroy', $model->idacad),
            ]);
        })
        ->addIndexColumn()
        ->rawColumns(['action'])
        ->make('true');
    }
}

resources/views/pages/academicyear/form.blade.php
{!! Form::model($model, [
'route' => $model->exists ? ['academicyear.update', $model->idacad] : 'academicyear.store',
'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

<div class="col-md-12">
    <div class="form-group">
        <label>Tahun Akademik</label>
        {{ Form::text('tahun_akademik', null, ['class' => 'form-control', 'id' => 'tahun_akademik', 'placeholder' => 'contoh : 2020/2021 ']) }}
    </div>
</div>

{!! Form::close() !!}

resources/views/pages/academicyear/index.blade.php
@extends('layout/nav_side_foot')
@section('title','SIN | Mata Kuliah')
@section('container')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">DATA TAHUN AKADEMIK</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Data Tahun Akademik</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Tahun Akademik</h3>
                <div class="float-sm-right">
                <a href="{{ route('academicyear.create') }}" class="btn btn-primary btn-sm float-sm-right modal-show" title="Tambah Data Tahun Akademik">
                    <i class="fas fa-plus"></i>  Tambah
                </a>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">

                  <thead>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Akademik</th>
                    <th>Tahun Akademik</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>

                  <tbody></tbody>

                  <tfoot>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Akademik</th>
                    <th>Tahun Akademik</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  @endsection
  @push('js')
  <script>
  $(function () {
    $("#table").DataTable({
      processing: true,
      serverSide: true,
      responsive: true,
      ajax: "{{ route('data.academicyear') }}",
      columns: [
        {data: 'DT_RowIndex', name: 'idacad'},
        {data: 'idacad', name: 'idacad'},
        {data: 'tahun_akademik', name: 'tahun_akademik'},
        {data: 'action', name: 'action'}
      ]

    });
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
  </script>
  @endpush