routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Session::has('login')) {
        return redirect('dashboard');
    }
    return redirect('login');
});
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/doLogin', 'AuthController@login')->name('doLogin');
Route::get('/logout', 'AuthController@logout')->name('logout');


//course
Route::resource('course', 'CourseController');
Route::get('/data/course', 'CourseController@dataTable')->name('data.course');

//lecturer
Route::resource('lecturer', 'LecturerController');
Route::get('/data/lecturer', 'LecturerController@dataTable')->name('data.lecturer');

//collegestudent
Route::resource('collegestudent', 'CollegeStudentController');
Route::get('/data/collegestudent', 'CollegeStudentController@dataTable')->name('data.collegestudent');

//grade
Route::resource('grade', 'GradeController');
Route::get('/data/grade', 'GradeController@dataTable')->name('data.grade');

//academicyear
Route::resource('academicyear', 'AcademicyearController');
Route::get('/data/academicyear', 'AcademicyearController@dataTable')->name('data.academicyear');

//teach
Route::resource('teach', 'TeachController');
Route::get('/data/teach', 'TeachController@dataTable')->name('data.teach');

//user
Route::resource('user', 'UserController');
Route::get('/data/user', 'UserController@dataTable')->name('data.user');

//auth

app/Teach.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teach extends Model
{
    protected $table = 'teachs';
    protected $primaryKey = 'idteachs';
    protected $guarded = [];
}

app/Http/Controllers/TeachController.php
<?php

namespace App\Http\Controllers;

use App\Lecturer;
use App\Course;
use App\Academicyear;
use App\Teach;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;

class TeachController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Teach::all();
        return view('pages.teach.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Teach();
        $dosen = Lecturer::all();
        $matkul = Course::all();
        $akademik = Academicyear::orderBy("tahun_akademik", "asc")->get();
        $selectDosen = [];
        $selectMatkul = [];
        $selectAkademik = [];
        foreach ($dosen as $dosen) {
            $selectDosen[$dosen->nidn] = $dosen->nama_dosen;
        }

        foreach ($matkul as $matkul) {
            $selectMatkul[$matkul->kode_matkul] = $matkul->mata_kuliah;
        }

        foreach ($akademik as $akademik) {
            $selectAkademik[$akademik->idacad] = $akademik->tahun_akademik;
        }
        return view('pages.teach.form', compact('model', 'selectDosen', 'selectMatkul', 'selectAkademik'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'nidn' => 'required',
        //     'kode_matkul' => 'required',
        //     'idacad' => 'required'
        // ]);
        $model = Teach::insert([
            [
                'nidn' => $request->nidn,
                'kode_matkul' => $request->kode_matkul,
                'idacad' => $request->idacad
            ]
        ]);
        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teach  $teach
     * @return \Illuminate\Http\Response
     */
    public function show(Teach $teach)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teach  $teach
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Teach::findOrFail($id);
        $dosen = Lecturer::all();
        $matkul = Course::all();
        $akademik = Academicyear::orderBy("tahun_akademik", "asc")->get();
        $selectDosen = [];
        $selectMatkul = [];
        $selectAkademik = [];
        foreach ($dosen as $dosen) {
            $selectDosen[$dosen->nidn] = $dosen->nama_dosen;
        }

        foreach ($matkul as $matkul) {
            $selectMatkul[$matkul->kode_matkul] = $matkul->mata_kuliah;
        }

        foreach ($akademik as $akademik) {
            $selectAkademik[$akademik->idacad] = $akademik->tahun_akademik;
        }
        return view('pages.teach.form', compact('model', 'selectDosen', 'selectMatkul', 'selectAkademik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teach  $teach
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Teach::findOrFail($id);
        $model->nidn = $request->nidn;
        $model->kode_matkul = $request->kode_matkul;
        $model->idacad = $request->idacad;
        $model->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teach  $teach
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Teach::findOrFail($id);
        $model->delete();
    }

    public function dataTable()
    {
        $model = Teach::join('lecturers', 'lecturers.nidn', '=', 'teachs.nidn')
            ->join('courses', 'courses.kode_matkul', '=', 'teachs.kode_matkul')
            ->join('academicyears', 'academicyears.idacad', '=', 'teachs.idacad')
            ->select('teachs.*', 'lecturers.*', 'courses.*', 'academicyears.*')
            ->get();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layout._actionteach', [
                    'model' => $model,
                    'url_edit' => route('teach.edit', $model->idteachs),
                    'url_destroy' => route('teach.destroy', $model->idteachs),
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make('true');
    }
}

resources/views/pages/teach/form.blade.php
{!! Form::model($model, [
'route' => $model->exists ? ['teach.update', $model->idteachs] : 'teach.store',
'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

<div class="col-md-12">
    <div class="form-group">
        <label>Pengampu</label>
        {{ Form::select('nidn', $selectDosen, null, ['class' => 'form-control', 'id' => 'nidn', 'placeholder' => 'Pilih Pengampu']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Mata Kuliah</label>
        {{ Form::select('kode_matkul', $selectMatkul, null, ['class' => 'form-control', 'id' => 'kode_matkul', 'placeholder' => 'Pilih Matkul']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Tahun Akademik</label>
        {{ Form::select('idacad', $selectAkademik, null, ['class' => 'form-control', 'id' => 'idacad', 'placeholder' => 'Pilih Tahun Akademik']) }}
    </div>
</div>


{!! Form::close() !!}

resources/views/pages/teach/index.blade.php
@extends('layout/nav_side_foot')
@section('title','SIN | Mata Kuliah')
@section('container')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">DATA PENGAMPU</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Data Pengampu</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Pengampu</h3>
                <div class="float-sm-right">
                <a href="{{ route('teach.create') }}" class="btn btn-primary btn-sm float-sm-right modal-show" title="Tambah Data Pengampu">
                    <i class="fas fa-plus"></i>  Tambah
                </a>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">

                  <thead>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Pengampu</th>
                    <th>Pengampu</th>
                    <th>Mata Kuliah</th>
                    <th>Tahun Akademik</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>

                  <tbody></tbody>

                  <tfoot>
                  <tr>
                    <th width="20">No.</th>
                    <th>ID Pengampu</th>
                    <th>Pengampu</th>
                    <th>Mata Kuliah</th>
                    <th>Tahun Akademik</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  @endsection
  @push('js')
  <script>
  $(function () {
    $("#table").DataTable({
      processing: true,
      serverSide: true,
      responsive: true,
      ajax: "{{ route('data.teach') }}",
      columns: [
        {data: 'DT_RowIndex', name: 'idteachs'},
        {data: 'idteachs', name: 'idteachs'},
        {data: 'nama_dosen', name: 'nama_dosen'},
        {data: 'mata_kuliah', name: 'mata_kuliah'},
        {data: 'tahun_akademik', name: 'tahun_akademik'},
        {data: 'action', name: 'action'}
      ]

    });
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
  </script>
  @endpush