routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Session::has('login')) {
        return redirect('dashboard');
    }
    return redirect('login');
});
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/doLogin', 'AuthController@login')->name('doLogin');
Route::get('/logout', 'AuthController@logout')->name('logout');


//course
Route::resource('course', 'CourseController');
Route::get('/data/course', 'CourseController@dataTable')->name('data.course');

//lecturer
Route::resource('lecturer', 'LecturerController');
Route::get('/data/lecturer', 'LecturerController@dataTable')->name('data.lecturer');

//collegestudent
Route::resource('collegestudent', 'CollegeStudentController');
Route::get('/data/collegestudent', 'CollegeStudentController@dataTable')->name('data.collegestudent');

//grade
Route::resource('grade', 'GradeController');
Route::get('/data/grade', 'GradeController@dataTable')->name('data.grade');

//academicyear
Route::resource('academicyear', 'AcademicyearController');
Route::get('/data/academicyear', 'AcademicyearController@dataTable')->name('data.academicyear');

//teach
Route::resource('teach', 'TeachController');
Route::get('/data/teach', 'TeachController@dataTable')->name('data.teach');

//user
Route::resource('user', 'UserController');
Route::get('/data/user', 'UserController@dataTable')->name('data.user');

//auth

app/CollegeStudent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CollegeStudent extends Model
{
    protected $table = 'collegestudents';
    protected $primaryKey = 'nim';
    public $incrementing = false;
    protected $guarded = [];
}

app/Http/Controllers/CollegeStudentController.php
<?php

namespace App\Http\Controllers;

use App\CollegeStudent;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;

class CollegeStudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = CollegeStudent::all();
        return view('pages.collegestudent.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new CollegeStudent();
        return view('pages.collegestudent.form', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nim' => 'required|min:10|max:10',
            'nama' => 'required|max:100',
            'kelas' => 'required'
        ]);

        $model = CollegeStudent::create($request->all());
        return $model;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CollegeStudent  $collegeStudent
     * @return \Illuminate\Http\Response
     */
    public function show(CollegeStudent $collegeStudent)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CollegeStudent  $collegeStudent
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = CollegeStudent::findOrFail($id);
        return view('pages.collegestudent.form', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CollegeStudent  $collegeStudent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = CollegeStudent::findOrFail($id);
        $model->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CollegeStudent  $collegeStudent
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = CollegeStudent::findOrFail($id);
        $model->delete();
    }

    public function dataTable()
    {
        $model = CollegeStudent::query();
        return DataTables::of($model)
        ->addColumn('action', function ($model){
            return view('layout._actioncollegestudent', [
                'model' => $model,
                'url_edit' => route('collegestudent.edit', $model->nim),
                'url_destroy' => route('collegestudent.destroy', $model->nim),
            ]);
        })
        ->addIndexColumn()
        ->rawColumns(['action'])
        ->make('true');
    }
}

resources/views/pages/collegestudent/form.blade.php
{!! Form::model($model, [
  'route' => $model->exists ? ['collegestudent.update', $model->nim] : 'collegestudent.store',
  'method' => $model->exists ? 'PUT' : 'POST'
]) !!} 
            <div class="form-group">
              <label>NIM</label>
              {!! Form::text('nim', null, ['class' => 'form-control', 'id' => 'nim']) !!}
            </div>
            <div class="form-group">
              <label>Nama Mahasiswa</label>
              {!! Form::text('nama', null, ['class' => 'form-control', 'id' => 'nama']) !!}
            </div>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Program Studi</label>
                {!! Form::select('program_studi', ['Teknik Informatika' => 'Teknik Informatika', 'Sistem Informasi' => 'Sistem Informasi', 'Manajemen Informatika' => 'Manajemen Informatika'], 'program_studi', ['class' => 'form-control', 'id' => 'program_studi']) !!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Kelas</label>
                {!! Form::text('kelas', null, ['class' => 'form-control', 'id' => 'kelas', 'placeholder' => 'Contoh : TI-VII B']) !!}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Jenis Kelamin</label>
                {!! Form::select('jk', ['laki-laki' => 'Laki-Laki', 'perempuan' => 'Perempuan'], 'laki-laki', ['class' => 'form-control', 'id' => 'jk']) !!}
            </div>
        </div>
    </div>

{!! Form::close() !!}

resources/views/pages/collegestudent/index.blade.php
@extends('layout/nav_side_foot')
@section('title','SIN | Data Mahasiswa')
@section('container')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">DATA MAHASISWA</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Data Mahasiswa</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid" >
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Mahasiswa</h3>
                <div class="float-sm-right">
                  <a href="{{ route('collegestudent.create') }}" class="btn btn-primary btn-sm float-sm-right modal-show" title="Tambah Data Mahasiswa">
                    <i class="fas fa-plus"></i>  Tambah
                  </a>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">

                  <thead>
                  <tr>
                    <th width="20">No.</th>
                    <th>NIM</th>
                    <th>Nama Mahasiswa</th>
                    <th>Program Studi</th>
                    <th>Kelas</th>
                    <th>Jenis Kelamin</th>
                    <th>Aksi</th>
                  </tr>
                  </thead>

                  <tbody><tfoot>
                  <tr>
                    <th>No.</th>
                    <th>NIM</th>
                    <th>Nama Mahasiswa</th>
                    <th>Program Studi</th>
                    <th>Kelas</th>
                    <th>Jenis Kelamin</th>
                    <th>Aksi</th>
                  </tr>
                  </tfoot>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection
@push('js')
  <script>
  $(function () {
    $("#table").DataTable({
      processing: true,
      serverSide: true,
      responsive: true,
      ajax: "{{ route('data.collegestudent') }}",
      columns: [
        {data: 'DT_RowIndex', name: 'nim'},
        {data: 'nim', name: 'nim'},
        {data: 'nama', name: 'nama'},
        {data: 'program_studi', name: 'program_studi'},
        {data: 'kelas', name: 'kelas'},
        {data: 'jk', name: 'jk'},
        {data: 'action', name: 'action'}
      ]

    });
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
  </script>
  @endpush